/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      archive.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

#include "egpack.h"

/*!
 * 
 */
egpack_status egpack_archive( char * source, FILE * destination )
{
    struct stat   stat_buf;
    egpack_status status;
    egpack_header header;
    
    if( stat( source, &stat_buf ) != 0 )
    {
        return EGPACK_ERROR_STAT;
    }
    
    memset( &header, 0, sizeof( egpack_header ) );
    memcpy( &( header.id ), EGPACK_FILE_ID, 4 );
    
    header.ctime = time( NULL );
    status       = EGPACK_OK;
    
    fwrite( &header, sizeof( egpack_header ), 1, destination );
    
    if( S_ISDIR( stat_buf.st_mode ) )
    {
        DEBUG( "Archiving directory" );
        
        status = egpack_archive_dir( source, 0, destination );
    }
    else if( S_ISREG( stat_buf.st_mode ) )
    {
        DEBUG( "Archiving regular file" );
        
        status = egpack_archive_file( source, 0, destination );
    }
    else
    {
        return EGPACK_ERROR_INVALID_FILE;
    }
    
    return status;
}

/*!
 * 
 */
egpack_status egpack_archive_file( char * filename, unsigned int depth, FILE * destination )
{
    struct stat              stat_buf;
    egpack_header_entry      entry;
    egpack_header_entry_file file;
    unsigned int             i;
    unsigned int             length;
    double                   hsize;
    char                     unit[ 3 ] = { 0, 0, 0 };
    FILE                   * fp;
    uint8_t                  buffer[ EGPACK_BUFFER_LENGTH ];
    
    if( stat( filename, &stat_buf ) != 0 )
    {
        return EGPACK_ERROR_STAT;
    }
    
    DEBUG( "Opening file handle" );
    
    if( NULL == ( fp = fopen( filename, "rb" ) ) )
    {
        return EGPACK_ERROR_FOPEN;
    }
    
    memset( &entry, 0, sizeof( egpack_header_entry ) );
    memset( &file,  0, sizeof( egpack_header_entry_file ) );
    
    length = strlen( filename );
    
    for( i = length; i > 0; i-- )
    {
        if( filename[ i - 1 ] == EGPACK_DIR_SEPARATOR_CHAR )
        {
            break;
        }
    }
    
    entry.type  = EGPACK_ENTRY_TYPE_FILE;
    entry.depth = depth;
    file.size   = stat_buf.st_size;
    file.ctime  = stat_buf.st_ctime;
    file.mtime  = stat_buf.st_mtime;
    file.atime  = stat_buf.st_atime;
    file.mode   = stat_buf.st_mode;
    file.uid    = stat_buf.st_uid;
    file.gid    = stat_buf.st_gid;
    
    egpack_file_md5_checksum( fp, ( char * )&( file.md5 ) );
    
    strcpy( ( char * )( file.name ), filename + i );
    
    if( file.size < 1000000 )
    {
        hsize = ( double )file.size / ( double )1000;
        
        strcpy( unit, "KB" );
    }
    else if( file.size < 1000000000 )
    {
        hsize = ( ( double )file.size / ( double )1000 ) / ( double )1000;
        
        strcpy( unit, "MB" );
    }
    else
    {
        hsize = ( ( ( double )file.size / ( double )1000 ) / ( double )1000 ) / ( double )1000;
        
        strcpy( unit, "GB" );
    }
    
    DEBUG
    (
        "File infos:\n"
        "    - Base name:         %s\n"
        "    - Depth:             %u\n"
        "    - Size:              %.02f %s\n"
        "    - Creation time:     %lu\n"
        "    - Modification time: %lu\n"
        "    - Access time:       %lu\n"
        "    - Mode:              0x%X\n"
        "    - UID:               %u\n"
        "    - GID:               %u",
        file.name,
        depth,
        hsize,
        unit,
        file.ctime,
        file.mtime,
        file.atime,
        file.mode,
        file.uid,
        file.gid
    );
    
    fwrite( &entry, sizeof( egpack_header_entry ),      1, destination );
    fwrite( &file,  sizeof( egpack_header_entry_file ), 1, destination );
    
    DEBUG( "Writing file data" );
    while( ( length = fread( buffer, sizeof( uint8_t ), EGPACK_BUFFER_LENGTH, fp ) ) )
    {
        fwrite( buffer, sizeof( uint8_t ), length, destination );
    }
    
    DEBUG( "Closing file handle" );
    fclose( fp );
    
    return EGPACK_OK;
}

/*!
 * 
 */
egpack_status egpack_archive_dir( char * dirname, unsigned int depth, FILE * destination )
{
    struct stat         stat_buf;
    DIR               * dp;
    struct dirent     * ep;
    egpack_status       status;
    size_t              path_length;
    char              * filename;
    egpack_header_entry entry;
    
    path_length = strlen( dirname ) + FILENAME_MAX + 2;
    
    if( NULL == ( filename = calloc( sizeof( char ), path_length ) ) )
    {
        return EGPACK_ERROR_MALLOC;
    }
    
    DEBUG( "Opening directory pointer" );
    
    if( NULL == ( dp = opendir( dirname ) ) )
    {
        return EGPACK_ERROR_OPENDIR;
    }
    
    memset( &entry, 0, sizeof( egpack_header_entry ) );
    
    entry.type  = EGPACK_ENTRY_TYPE_DIR;
    entry.depth = depth;
    
    fwrite( &entry, sizeof( egpack_header_entry ), 1, destination );
    
    status = EGPACK_OK;
    
    while( ( ep = readdir( dp ) ) )
    {
        memset( filename, 0, path_length );
        strcpy( filename, dirname );
        strcat( filename, EGPACK_DIR_SEPARATOR );
        strcat( filename, ep->d_name );
        
        if( strcmp( ep->d_name, "." ) == 0 )
        {
            DEBUG( "Skipping '.'" );
            continue;
        }
        else if( strcmp( ep->d_name, ".." ) == 0 )
        {
            DEBUG( "Skipping '..'" );
            continue;
        }
        else
        {
            if( stat( filename, &stat_buf ) != 0 )
            {
                free( filename );
                closedir( dp );
                
                return EGPACK_ERROR_STAT;
            }
            
            if( S_ISDIR( stat_buf.st_mode ) )
            {
                DEBUG( "Archiving directory: %s", filename );
                
                status = egpack_archive_dir( filename, depth + 1, destination );
                
                if( status != EGPACK_OK )
                {
                    free( filename );
                    closedir( dp );
                    
                    return status;
                }
            }
            else if( S_ISREG( stat_buf.st_mode ) )
            {
                DEBUG( "Archiving file: %s", filename );
                
                status = egpack_archive_file( filename, depth + 1, destination );
                
                if( status != EGPACK_OK )
                {
                    free( filename );
                    closedir( dp );
                    
                    return status;
                }
            }
            else
            {
                DEBUG( "Skipping invalid file: %s", filename );
                continue;
            }
            
            ( void )depth;
            ( void )destination;
        }
    }
    
    free( filename );
    DEBUG( "Closing directory pointer" );
    closedir( dp );
    
    return status;
}
