/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        md5.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    MD5 functions
 */

/* Local includes */
#include "egpack.h"

/* Private variables */
static unsigned int __percent = 0;
static char         __last_md5[ MD5_DIGEST_LENGTH * 2 + 1 ];
static FILE       * __last_fp;

/*!
 * 
 */
void egpack_file_md5_checksum( FILE * fp, char * hash )
{
    MD5_CTX             ctx;
    size_t              length;
    unsigned char       digest[ MD5_DIGEST_LENGTH ];
    char                tmp[ EGPACK_BUFFER_LENGTH ];
    char                hex[ 3 ];
    long                offset;
    unsigned int        i;
    unsigned long       size;
    unsigned long       read_ops;
    unsigned long       read_op;
    libprogressbar_args args;
    
    if( fp == __last_fp )
    {
        strcpy( hash, __last_md5 );
        return;
    }
    
    __last_fp = fp;
    __percent = 0;
    size      = fsize( fp );
    read_ops  = ceil( ( double )size / ( double )EGPACK_BUFFER_LENGTH );
    read_op   = 0;
    __percent = 0;
    
    if( libdebug_is_enabled() == false )
    {
        args.percent = &__percent;
        args.length  = 50;
        args.label   = "Checksumming: ";
        args.done    = "[OK]";
        
        libprogressbar_create_progressbar( ( void * )( &args ) );
    }
    
    offset = ftell( fp );
    
    fseek( fp, 0, SEEK_SET );
    MD5_Init( &ctx );
    
    while( ( length = fread( tmp, sizeof( char ), EGPACK_BUFFER_LENGTH, fp ) ) )
    {
        read_op++;
        
        MD5_Update( &ctx, tmp, length );
        
        if( read_ops > 1 )
        {
            __percent = ( ( double )read_op / ( double )read_ops ) * 100;
        }
    }
    
    MD5_Final( digest, &ctx );
    
    hex[ 3 ] = 0;
    
    for( i = 0; i < MD5_DIGEST_LENGTH; i++ )
    {
        sprintf( hex, "%02x", digest[ i ] );
        strcat( hash, hex );
        hash += 2;
    }
    
    hash -= MD5_DIGEST_LENGTH * 2;
    
    strcpy( __last_md5, hash );
    
    fseek( fp, offset, SEEK_SET );
    
    __percent = 100;
    
    libprogressbar_end();
}
